
// This file was auto-generated by ML.NET Model Builder. 

using TextSimilarity_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
TextSimilarity.ModelInput sampleData = new TextSimilarity.ModelInput()
{
    Desc1 = @"The driver of the truck escaped and is now being sought by the police, Supoyo said.",
    Desc2 = @"But police say the driver of the truck has not been found and is wanted for questioning.",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Similarity with predicted Similarity from sample data...\n\n");


Console.WriteLine($"Desc1: {@"The driver of the truck escaped and is now being sought by the police, Supoyo said."}");
Console.WriteLine($"Desc2: {@"But police say the driver of the truck has not been found and is wanted for questioning."}");
Console.WriteLine($"Similarity: {0.8F}");


var predictionResult = TextSimilarity.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Similarity: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

